// <auto-generated />
using System;
using AIdentities.Chat.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIdentities.Chat.Migrations
{
    [DbContext(typeof(ConversationDbContext))]
    [Migration("20230530154558_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("AIdentities.Shared.Features.CognitiveEngine.Memory.Conversation.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("AIdentities.Shared.Features.CognitiveEngine.Memory.Conversation.ConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorName")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAIGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("ConversationMessages");
                });

            modelBuilder.Entity("AIdentities.Shared.Features.CognitiveEngine.Memory.Conversation.ConversationMetadata", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AIdentityIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Humans")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MessageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConversationId");

                    b.ToTable("ConversationMetadata");
                });

            modelBuilder.Entity("AIdentities.Shared.Features.CognitiveEngine.Memory.Conversation.ConversationMessage", b =>
                {
                    b.HasOne("AIdentities.Shared.Features.CognitiveEngine.Memory.Conversation.Conversation", null)
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId");
                });

            modelBuilder.Entity("AIdentities.Shared.Features.CognitiveEngine.Memory.Conversation.ConversationMetadata", b =>
                {
                    b.HasOne("AIdentities.Shared.Features.CognitiveEngine.Memory.Conversation.Conversation", null)
                        .WithOne("Metadata")
                        .HasForeignKey("AIdentities.Shared.Features.CognitiveEngine.Memory.Conversation.ConversationMetadata", "ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AIdentities.Shared.Features.CognitiveEngine.Memory.Conversation.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Metadata")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
