namespace AIdentities.Chat.Models;

/// <summary>
/// A chat message.
/// Usually belongs to a <see cref="Conversation"/>.
/// The message can be generated by the system or by a user.
/// A system generated message will have the <see cref="IsGenerated"/> property set to true and can be generated by an AIdentity.
/// If the message is generated by an AIdentity, the <see cref="AIDentityId"/> property will be set.
/// If the message is generated by a user, the <see cref="User"/> property will be set.
/// </summary>
public record ChatMessage
{
   /// <summary>
   /// The id of the chat message
   /// </summary>
   public Guid Id { get; set; } = Guid.NewGuid();

   /// <summary>
   /// The date and time the message was created.
   /// </summary>
   public DateTimeOffset CreationDate { get; set; } = DateTimeOffset.Now;

   /// <summary>
   /// True if the message was generated by the system.
   /// False if the message was generated by a user.
   /// </summary>
   public bool IsGenerated { get; set; }

   /// <summary>
   /// The user who sent the message.
   /// Null if the message was generated by the system (IsGenerated = true).
   /// </summary>
   public string? User { get; set; }

   /// <summary>
   /// The message text.
   /// </summary>
   public string? Message { get; set; }

   /// <summary>
   /// The Id of the AIdentity that sent the message.
   /// Null if the message was generated by the user (IsGenerated = false).
   /// </summary>
   public Guid? AIDentityId { get; set; }

   /// <summary>
   /// Custom user defined data that can be attached to a message.
   /// </summary>
   public Dictionary<string, object> Metadata { get; set; } = new();
}
