using Microsoft.AspNetCore.Http.Features;

namespace AIdentities.Shared.Features.CognitiveEngine.Memory.Conversation;

/// <summary>
/// A conversation message.
/// It's part of a <see cref="Conversation"/>.
/// The message can be generated by the AI or by a human reflected by the <see cref="IsAIGenerated"/> property.
/// If the message is generated by the AI, the <see cref="AuthorId"/> property will contain the AIdentity that generated the message.
/// If the message is generated by a human, the <see cref="AuthorId"/> property will contain the human Id that generated the message.
/// Features can be attached to a message and can be used by plugins to extend the functionality of the message.
/// </summary>
public record Message
{
   /// <summary>
   /// The message Id.
   /// </summary>
   public Guid Id { get; set; } = Guid.NewGuid();

   /// <summary>
   /// The date and time the message was created.
   /// </summary>
   public DateTimeOffset CreationDate { get; set; } = DateTimeOffset.Now;

   /// <summary>
   /// True if the message was generated by the AI.
   /// False if the message was generated by a user.
   /// Depending 
   /// </summary>
   public bool IsAIGenerated { get; set; }

   /// <summary>
   /// The message author.
   /// If IsGenerated is true, this refers to the AIdentity that generated the message.
   /// If IsGenerated is false, this refers to the user that generated the message.
   /// </summary>
   public Guid AuthorId { get; set; }

   /// <summary>
   /// The message text.
   /// </summary>
   public string? Text { get; set; }

   /// <summary>
   /// The features of the Conversation.
   /// This is an extension point Plugin developers can use this to manage custom features
   /// to conversations or access other plugins' features.
   /// </summary>
   public FeatureCollection? Features { get; set; }
}
