using AIdentities.Shared.Features.CognitiveEngine.Mission;
using AIdentities.Shared.Features.CognitiveEngine.Prompts;
using AIdentities.Shared.Features.CognitiveEngine.Thoughts;

namespace AIdentities.Shared.Features.CognitiveEngine.Skills;

public interface ISkill
{
   /// <summary>
   /// The unique identifier of the skill action instance.
   /// </summary>
   public Guid Id { get; }

   /// <summary>
   /// The name of the skill action.
   /// </summary>
   string Name { get; }

   /// <summary>
   /// Execute the skill action giving a natural language input.
   /// The natural language prompt can be generated by many sources, including user, other skills, thoughts, etc.
   /// While the skill is executing, it can stream back to the caller its thoughts.
   /// </summary>
   /// <param name="prompt">The natural language input generated by the AI agent.</param>
   /// <param name="executionContext">The execution context of the skill.</param>
   /// <param name="cancellationToken">A cancellation token.</param>
   /// <returns>A natural language stream of responses about the action outcome.</returns>
   IAsyncEnumerable<Thought> ExecuteAsync(Prompt prompt, SkillExecutionContext executionContext, CancellationToken cancellationToken);
}
