global using AIdentities.Shared.Features.AIdentities.Models;
global using AIdentities.Shared.Features.AIdentities.Services;
global using AIdentities.Shared.Plugins;
global using AIdentities.Shared.Plugins.Storage;
global using Microsoft.AspNetCore.Components.Forms;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
