namespace AIdentities.Shared.Features.CognitiveEngine.Mission;

/// <summary>
/// A mission artifact is a piece of information that has been generated by a mission execution.
/// Even an incomplete mission execution can generate artifacts.
/// </summary>
public record MissionArtifact
{
   /// <summary>
   /// The id of the mission artifact.
   /// </summary>
   public Guid Id { get; set; } = Guid.NewGuid();

   /// <summary>
   /// The name of the mission artifact.
   /// </summary>
   public string Name { get; set; } = "";

   /// <summary>
   /// The description of the mission artifact.
   /// </summary>
   public string Description { get; set; } = "";
}
