using AIdentities.Shared.Common;

namespace AIdentities.Shared.Features.CognitiveEngine.Mission;

/// <summary>
/// A mission artifact is a piece of information that has been generated by a mission execution.
/// Even an incomplete mission execution can generate artifacts.
/// </summary>
public record MissionArtifact : Entity
{
   public string Name { get; set; } = "";
   public string Description { get; set; } = "";
}
