namespace AIdentities.Shared.Features.CognitiveEngine.Models;

/// <summary>
/// This class represents the result of a mission.
/// </summary>
public record MissionResult
{
   /// <summary>
   /// The mission leader.
   /// Any mission has an AIdentity that is the leader of the mission.
   /// </summary>
   public AIdentity MissionLeader { get; set; } = default!;

   /// <summary>
   /// True if the mission was successful, false otherwise.
   /// </summary>
   public bool Success { get; set; }

   /// <summary>
   /// A list of artifacts produced by the mission.
   /// An artifact is a piece of information that has been generated by a mission execution.
   /// Even an incomplete mission execution can generate artifacts.
   /// </summary>
   public List<MissionArtifact> MissionArtifacts { get; set; } = new();
}
