namespace AIdentities.Shared.Features.CognitiveEngine;

/// <summary>
/// This class is responsible for creating a specific cognitive engine for a specific AIdentity.
/// </summary>
public interface ICognitiveEngineFactory
{
   /// <summary>
   /// The type of the cognitive engine that will be generated by this provider.
   /// </summary>
   public Type CognitiveEngineType { get; }

   /// <summary>
   /// Creates the cognitive engine for the specified AIdentity.
   /// </summary>
   /// <param name="aIdentity">The AIdentity for which the cognitive engine must be created.</param>
   /// <returns>The AIdentity cognitive engine.</returns>
   ICognitiveEngine CreateCognitiveEngine(AIdentity aIdentity);
}
