namespace AIdentities.Shared.Plugins.Connectors.Completion;

/// <summary>
/// A response generated by a completion connector.
/// The only expected result from all the required property is <see cref="GeneratedMessage"/>.
/// Other properties are optional and depend on the <see cref="ICompletionConnector"/> capabilities.
/// </summary>
public record CompletionResponse
{
   /// <summary>
   /// The model id used to generate the response.
   /// </summary>
   public string? ModelId { get; init; }

   /// <summary>
   /// The generated response.
   /// This is the only expected property that should be filled by any Conversational Connector.
   /// </summary>
   public string? GeneratedMessage { get; init; }

   /// <summary>
   /// The number of tokens used by the prompt.
   /// </summary>
   public int? PromptTokens { get; set; }

   /// <summary>
   /// The number of tokens generated by the response.
   /// </summary>
   public int? CompletionTokens { get; init; }

   /// <summary>
   /// The total number of used tokens, given by the prompt and the response.
   /// </summary>
   public int? TotalTokens { get; init; }

   /// <summary>
   /// The time it took to generate the response.
   /// </summary>
   public TimeSpan ResponseTime { get; init; }

   /// <summary>
   /// The finish reason of the response.
   /// </summary>
   public string? FinishReason { get; init; }
}
