namespace AIdentities.Shared.Features.CognitiveEngine.Prompts;

/// <summary>
/// This prompt is the raw prompt generated by the user.
/// </summary>
/// <param name="UserId">The Id of the user that generated the prompt.</param>
/// <param name="Text">The text of the prompt.</param>
public record UserPrompt(Guid UserId, string Text) : Prompt(Text) { }
